# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: build
    steps:
    - checkout: self
    - script: |
        echo "Run your build here"
        # e.g., npm ci && npm run build
      displayName: Build app
    - publish: $(System.DefaultWorkingDirectory)
      artifact: drop

- stage: Deploy
  displayName: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployToDev
    displayName: Deploy to Dev
    environment: 'asd3'           # << must match the Environment name
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          # Example: deploy to Azure Web App (replace with your target)
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'sc-azure-sp'   # your service connection
              appName: 'my-webapp-name'
              package: '$(Pipeline.Workspace)/drop/**.zip'